"""Mark a Beaver Bill phase complete after the gate passes.

Only this script may write the generated sections of process.md and the
status fields of progress/phase-status.json. It re-runs the phase checks
first and refuses to write anything when a required check fails.

Usage:
    python3 scripts/mark_phase_complete.py <phase-id> [--evidence PATH]...
        [--status-file PATH] [--process-file PATH] [--dry-run]

Prints the completion message from plan.md on success.
"""

from __future__ import annotations

import argparse
import copy
import datetime
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__))))
from beaverbill_phase_check import run_git, run_phase  # noqa: E402

PROGRESS_START = "<!-- AUTO-PROGRESS-START -->"
PROGRESS_END = "<!-- AUTO-PROGRESS-END -->"
LOG_START = "<!-- AUTO-COMPLETION-LOG-START -->"
LOG_END = "<!-- AUTO-COMPLETION-LOG-END -->"
GENERATED_NOTE = "<!-- This section is generated by scripts/mark_phase_complete.py. Do not edit manually. -->"


def ordered_phase_ids(status):
    return sorted(status["phases"], key=lambda pid: int(pid.split("-")[1]))


def replace_block(text, start, end, body_lines):
    if start not in text or end not in text:
        raise ValueError(f"markers missing: {start} / {end}")
    before, _, rest = text.partition(start)
    _, _, after = rest.partition(end)
    block = "\n".join([start, GENERATED_NOTE, *body_lines, end])
    return before + block + after


def progress_block(status):
    lines = [
        f"- Current Phase: {status['current_phase']} ({status['phases'][status['current_phase']]['title']})",
    ]
    for pid in ordered_phase_ids(status):
        phase = status["phases"][pid]
        lines.append(f"- {pid} ({phase['title']}): {phase['status']}")
    return lines


def render_process(process_text, status):
    completed = [pid for pid in ordered_phase_ids(status) if status["phases"][pid]["status"] == "completed"]
    log_lines = ["No phase has been completed by the automatic phase gate yet."] if not completed else []
    for pid in completed:
        phase = status["phases"][pid]
        log_lines.append(
            f"- {pid} ({phase['title']}) completed at {phase['completed_at']} "
            f"in commit {phase['commit']}."
        )
    text = replace_block(process_text, PROGRESS_START, PROGRESS_END, progress_block(status))
    return replace_block(text, LOG_START, LOG_END, log_lines)


def atomic_write(path, text):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
    os.replace(tmp, path)


def completion_message(phase, commit, evidence, next_id, next_title):
    return "\n".join(
        [
            "PHASE COMPLETE",
            f"Phase: {phase['id']} - {phase['title']}",
            "Status: completed",
            f"Commit: {commit}",
            "Process file: updated automatically",
            "Progress file: updated automatically",
            f"Evidence: {', '.join(evidence) if evidence else 'none recorded'}",
            f"Next phase: {next_id} - {next_title}",
            "Next action: read plan.md and process.md, then start the next phase.",
        ]
    )


def mark_complete(phase_id, root, evidence, status_file, process_file, dry_run=False):
    report = run_phase(phase_id, root)
    failed = [c["name"] for c in report["checks"] if c["required"] and not c["passed"]]
    if failed:
        return False, report, None
    with open(status_file, encoding="utf-8") as fh:
        status = json.load(fh)
    if phase_id not in status["phases"]:
        raise ValueError(f"unknown phase: {phase_id}")
    if status["phases"][phase_id]["status"] == "completed":
        raise ValueError(f"{phase_id} is already completed")
    commit = run_git(root, "rev-parse", "HEAD")
    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    updated = copy.deepcopy(status)
    updated["phases"][phase_id].update({"status": "completed", "completed_at": now, "commit": commit, "evidence": evidence})
    ids = ordered_phase_ids(updated)
    next_id = ids[ids.index(phase_id) + 1] if ids.index(phase_id) + 1 < len(ids) else None
    if next_id and updated["phases"][next_id]["status"] == "not_started":
        updated["phases"][next_id]["status"] = "in_progress"
    updated["current_phase"] = next_id or phase_id
    with open(process_file, encoding="utf-8") as fh:
        process_text = render_process(fh.read(), updated)
    if not dry_run:
        atomic_write(status_file, json.dumps(updated, indent=2) + "\n")
        atomic_write(process_file, process_text)
    next_title = updated["phases"][next_id]["title"] if next_id else "none"
    message = completion_message(updated["phases"][phase_id], commit, evidence, next_id or "none", next_title)
    return True, report, message


def main(argv=None):
    parser = argparse.ArgumentParser(description="Mark a phase complete after the gate passes.")
    parser.add_argument("phase", help="phase id, for example phase-0")
    parser.add_argument("--evidence", action="append", default=[], help="evidence path (repeatable)")
    parser.add_argument("--root", default=os.getcwd(), help="repository root")
    parser.add_argument("--status-file", default=None)
    parser.add_argument("--process-file", default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)
    status_file = args.status_file or os.path.join(args.root, "progress/phase-status.json")
    process_file = args.process_file or os.path.join(args.root, "process.md")
    try:
        ok, report, message = mark_complete(args.phase, args.root, args.evidence, status_file, process_file, args.dry_run)
    except (OSError, ValueError) as exc:
        print(f"PHASE NOT COMPLETE\nPhase: {args.phase}\nError: {exc}")
        return 1
    if not ok:
        failed = [c["name"] for c in report["checks"] if c["required"] and not c["passed"]]
        print(f"PHASE NOT COMPLETE\nPhase: {args.phase}\nFailed checks: {', '.join(failed)}")
        print("Process file: not marked complete\nProgress file: not marked complete")
        print("Next action: fix the failed checks and run the phase gate again.")
        return 1
    print(message)
    return 0


if __name__ == "__main__":
    sys.exit(main())
